// Code generated by protoc-gen-go. DO NOT EDIT.
// source: model.proto

/*
Package model is a generated protocol buffer package.

It is generated from these files:
	model.proto

It has these top-level messages:
	Message
*/
package model

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// type Message struct {
// 	Query   string `protobuf:"bytes,1,opt,name=query" json:"query,omitempty"`
// 	Code    int32  `protobuf:"varint,2,opt,name=code" json:"code,omitempty"`
// 	Pbk     []byte `protobuf:"bytes,3,opt,name=pbk,proto3" json:"pbk,omitempty"`
// 	Sign    []byte `protobuf:"bytes,4,opt,name=sign,proto3" json:"sign,omitempty"`
// 	Value   string `protobuf:"bytes,5,opt,name=value" json:"value,omitempty"`
// 	Address string `protobuf:"bytes,6,opt,name=address" json:"address,omitempty"`
// 	Data    string `protobuf:"bytes,7,opt,name=data" json:"data,omitempty"`
// }

func (m *Message) Reset()                    { *m = Message{} }
func (m *Message) String() string            { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()               {}
func (*Message) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Message) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

func (m *Message) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Message) GetPbk() []byte {
	if m != nil {
		return m.Pbk
	}
	return nil
}

func (m *Message) GetSign() []byte {
	if m != nil {
		return m.Sign
	}
	return nil
}

func (m *Message) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *Message) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Message) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func init() {
	proto.RegisterType((*Message)(nil), "model.Message")
}

func init() { proto.RegisterFile("model.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 160 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x34, 0x8e, 0x41, 0xca, 0xc2, 0x30,
	0x10, 0x46, 0xc9, 0xdf, 0xa6, 0xe1, 0x1f, 0x5d, 0xc8, 0xe0, 0x62, 0x96, 0xc1, 0x55, 0x56, 0x6e,
	0x3c, 0x87, 0x9b, 0xdc, 0x20, 0x35, 0x43, 0x11, 0xab, 0xa9, 0x49, 0x2b, 0x78, 0x18, 0xef, 0x2a,
	0x99, 0xe2, 0xee, 0xbd, 0x8f, 0xe1, 0x31, 0xb0, 0xb9, 0xa7, 0xc8, 0xe3, 0x71, 0xca, 0x69, 0x4e,
	0xa8, 0x45, 0x0e, 0x1f, 0x05, 0xe6, 0xcc, 0xa5, 0x84, 0x81, 0x71, 0x0f, 0xfa, 0xb9, 0x70, 0x7e,
	0x93, 0xb2, 0xca, 0xfd, 0xfb, 0x55, 0x10, 0xa1, 0xbd, 0xa4, 0xc8, 0xf4, 0x67, 0x95, 0xd3, 0x5e,
	0x18, 0x77, 0xd0, 0x4c, 0xfd, 0x8d, 0x1a, 0xab, 0xdc, 0xd6, 0x57, 0xac, 0x57, 0xe5, 0x3a, 0x3c,
	0xa8, 0x95, 0x49, 0xb8, 0xf6, 0x5e, 0x61, 0x5c, 0x98, 0xf4, 0xda, 0x13, 0x41, 0x02, 0x13, 0x62,
	0xcc, 0x5c, 0x0a, 0x75, 0xb2, 0xff, 0xb4, 0x36, 0x62, 0x98, 0x03, 0x19, 0x99, 0x85, 0xfb, 0x4e,
	0xbe, 0x3d, 0x7d, 0x03, 0x00, 0x00, 0xff, 0xff, 0x93, 0xb2, 0xc5, 0x44, 0xbc, 0x00, 0x00, 0x00,
}
