// Code generated by protoc-gen-go. DO NOT EDIT.
// source: model.proto

/*
Package model is a generated protocol buffer package.

It is generated from these files:
	model.proto

It has these top-level messages:
	Peer
	Message
*/
package model

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// type Peer struct {
// 	Address    string `protobuf:"bytes,1,opt,name=address" json:"address,omitempty"`
// 	PortStatus int32  `protobuf:"varint,2,opt,name=portStatus" json:"portStatus,omitempty"`
// }

func (m *Peer) Reset()                    { *m = Peer{} }
func (m *Peer) String() string            { return proto.CompactTextString(m) }
func (*Peer) ProtoMessage()               {}
func (*Peer) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Peer) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Peer) GetPortStatus() int32 {
	if m != nil {
		return m.PortStatus
	}
	return 0
}

// type Message struct {
// 	Query      string  `protobuf:"bytes,1,opt,name=query" json:"query,omitempty"`
// 	Code       int32   `protobuf:"varint,2,opt,name=code" json:"code,omitempty"`
// 	Pbk        []byte  `protobuf:"bytes,3,opt,name=pbk,proto3" json:"pbk,omitempty"`
// 	Sign       []byte  `protobuf:"bytes,4,opt,name=sign,proto3" json:"sign,omitempty"`
// 	Value      string  `protobuf:"bytes,5,opt,name=value" json:"value,omitempty"`
// 	Address    string  `protobuf:"bytes,6,opt,name=address" json:"address,omitempty"`
// 	Data       string  `protobuf:"bytes,7,opt,name=data" json:"data,omitempty"`
// 	Token      string  `protobuf:"bytes,8,opt,name=token" json:"token,omitempty"`
// 	PortStatus int32   `protobuf:"varint,9,opt,name=portStatus" json:"portStatus,omitempty"`
// 	Peers      []*Peer `protobuf:"bytes,10,rep,name=peers" json:"peers,omitempty"`
// 	Start      int32   `protobuf:"varint,11,opt,name=start" json:"start,omitempty"`
// 	Limit      int32   `protobuf:"varint,12,opt,name=limit" json:"limit,omitempty"`
// }

func (m *Message) Reset()                    { *m = Message{} }
func (m *Message) String() string            { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()               {}
func (*Message) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Message) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

func (m *Message) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Message) GetPbk() []byte {
	if m != nil {
		return m.Pbk
	}
	return nil
}

func (m *Message) GetSign() []byte {
	if m != nil {
		return m.Sign
	}
	return nil
}

func (m *Message) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *Message) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Message) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func (m *Message) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *Message) GetPortStatus() int32 {
	if m != nil {
		return m.PortStatus
	}
	return 0
}

func (m *Message) GetPeers() []*Peer {
	if m != nil {
		return m.Peers
	}
	return nil
}

func (m *Message) GetStart() int32 {
	if m != nil {
		return m.Start
	}
	return 0
}

func (m *Message) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func init() {
	proto.RegisterType((*Peer)(nil), "model.Peer")
	proto.RegisterType((*Message)(nil), "model.Message")
}

func init() { proto.RegisterFile("model.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 245 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0x41, 0x4e, 0xc3, 0x30,
	0x10, 0x45, 0x95, 0x26, 0x6e, 0xe8, 0xa4, 0x0b, 0x34, 0x62, 0x31, 0x2b, 0x14, 0xba, 0xca, 0xaa,
	0x0b, 0xb8, 0x00, 0x17, 0x40, 0x42, 0xe1, 0x04, 0x2e, 0x1e, 0x55, 0x51, 0xd3, 0x3a, 0xd8, 0x13,
	0x24, 0xae, 0xc3, 0x49, 0x91, 0xc7, 0x45, 0x6a, 0xbb, 0xfb, 0xef, 0xdb, 0xf3, 0x35, 0xf3, 0xa1,
	0x39, 0x7a, 0xc7, 0xe3, 0x76, 0x0a, 0x5e, 0x3c, 0x1a, 0x85, 0xcd, 0x2b, 0x54, 0xef, 0xcc, 0x01,
	0x09, 0x6a, 0xeb, 0x5c, 0xe0, 0x18, 0xa9, 0x68, 0x8b, 0x6e, 0xd5, 0xff, 0x23, 0x3e, 0x02, 0x4c,
	0x3e, 0xc8, 0x87, 0x58, 0x99, 0x23, 0x2d, 0xda, 0xa2, 0x33, 0xfd, 0x85, 0xb3, 0xf9, 0x5d, 0x40,
	0xfd, 0xc6, 0x31, 0xda, 0x3d, 0xe3, 0x03, 0x98, 0xaf, 0x99, 0xc3, 0xcf, 0x39, 0x23, 0x03, 0x22,
	0x54, 0x9f, 0xde, 0xf1, 0x79, 0x56, 0x35, 0xde, 0x43, 0x39, 0xed, 0x0e, 0x54, 0xb6, 0x45, 0xb7,
	0xee, 0x93, 0x4c, 0xbf, 0xe2, 0xb0, 0x3f, 0x51, 0xa5, 0x96, 0xea, 0x94, 0xf7, 0x6d, 0xc7, 0x99,
	0xc9, 0xe4, 0x3c, 0x85, 0xcb, 0x5d, 0x97, 0xd7, 0xbb, 0x22, 0x54, 0xce, 0x8a, 0xa5, 0x5a, 0x6d,
	0xd5, 0x29, 0x43, 0xfc, 0x81, 0x4f, 0x74, 0x97, 0x33, 0x14, 0x6e, 0xae, 0x5a, 0xdd, 0x5e, 0x85,
	0x4f, 0x60, 0x26, 0xe6, 0x10, 0x09, 0xda, 0xb2, 0x6b, 0x9e, 0x9b, 0x6d, 0xee, 0x2e, 0x75, 0xd5,
	0xe7, 0x97, 0x14, 0x1c, 0xc5, 0x06, 0xa1, 0x46, 0xa7, 0x33, 0x24, 0x77, 0x1c, 0x8e, 0x83, 0xd0,
	0x3a, 0xbb, 0x0a, 0xbb, 0xa5, 0x96, 0xfe, 0xf2, 0x17, 0x00, 0x00, 0xff, 0xff, 0x01, 0xf9, 0x96,
	0x8d, 0x83, 0x01, 0x00, 0x00,
}
