image:
- Visual Studio 2017

environment:
  GOPATH: c:\gopath

install:
  - set PATH=C:\msys64\mingw64\bin;;%PATH% # for cgo
  - set PATH=%GOPATH%\bin;%PATH%
  - go get -u github.com/mh-cbon/go-libutp
  - go get -u github.com/jessevdk/go-flags
  - go get -u github.com/elazarl/goproxy
  - go get -u github.com/bradfitz/iter
  - go get -u github.com/gorilla/mux
  - go get -u github.com/golang/protobuf/proto
  - go get -u github.com/anacrolix/torrent/bencode
  - go get -u github.com/anacrolix/missinggo
  - go get -u github.com/mh-cbon/rendez-vous

build_script:
  - go test
  - go run main.go
