image:
- Visual Studio 2017

install:
  # - choco install make
  # specific to go
  - echo %PATH%
  - DIR C:\msys64
  - DIR C:\msys64\mingw64\bin
  - set PATH=C:\msys64\mingw64\bin;%GOPATH%\bin;%PATH%
  - go get -u github.com/mh-cbon/never-fail
  - never-fail go get -v -u -a -x github.com/anacrolix/go-libutp
  - go get -u github.com/jessevdk/go-flags
  - go get -u github.com/elazarl/goproxy
  - go get -u github.com/bradfitz/iter
  - go get -u github.com/gorilla/mux
  - go get -u github.com/golang/protobuf/proto
  - go get -u github.com/anacrolix/torrent
  - go get -u github.com/anacrolix/missinggo

# before_build:
#   # Workaround for CMake not wanting sh.exe on PATH for MinGW
#   - set PATH=%PATH:C:\Program Files (x86)\Git\bin;=%
#   - set PATH=C:\MinGW\bin;%PATH%

build_script:
  - go test
  - go run main.go
