image:
- Visual Studio 2017

install:
  - DIR C:\
  # - choco install make
  # - refreshenv
  # specific to go
  # - echo %PATH%
  # - set PATH=C:\msys64\usr\bin;%GOPATH%\bin;%PATH%
  - choco install mingw
  - refreshenv
  - DIR C:\
  - go get -u github.com/jessevdk/go-flags
  - go get -u github.com/elazarl/goproxy
  - go get -u github.com/bradfitz/iter
  - go get -u github.com/gorilla/mux
  - go get -u github.com/golang/protobuf/proto
  - go get -u github.com/anacrolix/torrent
  - go get -u github.com/anacrolix/missinggo
  - go get -u github.com/anacrolix/go-libutp

# before_build:
#   # Workaround for CMake not wanting sh.exe on PATH for MinGW
#   - set PATH=%PATH:C:\Program Files (x86)\Git\bin;=%
#   - set PATH=C:\MinGW\bin;%PATH%

build_script:
  - go test
  - go run main.go
